### ISSUE TITLE
Node not running

### ISSUE THREAD

**Issue by WoodyPhil** [fwrgit/resin-electronjs#53] opened 2017-09-24 09:51 UTC
When i put the electron files into the app directory it fire´s up the index.html but give me errors like 

![image](https://user-images.githubusercontent.com/7937191/30781390-6f168e0c-a11e-11e7-86b0-261d57e4bc0c.png)

In my opinion the node server is not running, but i have checked the environment variable

![image](https://user-images.githubusercontent.com/7937191/30781403-9849b18c-a11e-11e7-9a24-e76bd12c9385.png)

I´m stuck with that for a long time some help would be really nice

**Comment by curcuz** [comment] 2017-11-15 12:44
hi @WoodyPhil the errors you showed are not related with node running or not - in fact, it **is** running and that's the cause of your issue. Please have a read here about jQuery being confused on electron https://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined

**Comment by curcuz** [comment] 2018-01-03 21:37
closing since the user didn't reply in a long time

**Closed as completed by curcuz** 2018-01-03 21:37 UTC
