### ISSUE TITLE
Audio not working on Electron

### ISSUE THREAD

**Issue by edoardo849** [fwrgit/resin-electronjs#10] opened 2016-09-17 10:04 UTC
Hello @curcuz  ! So after several trials I'm still having issues with audio. 

I have a USB Microphone and a speaker connected to the jack.

Input audio works with your default Dockerfile but the audio does not. Now if I install omxplayer I can play audio from the terminal. However, still no luck in Electron. If I install alsa-utils and set up /etc/asound.conf like this:

```
pcm.!default {
    type hw
    card 1
}
ctl.!default {
    type hw           
    card 0
}
```

the audio works fine on Electron, but the input (microphone) does not. I have also tried to use this config:

```
pcm.!default {
    type asym
    playback.pcm "hw:0,0"
    capture.pcm "hw:1,1"
}
```

and

```
pcm.!default {
    type asym
    playback.pcm "hw:1,1"
    capture.pcm "hw:0,0"
}
```

but still no luck.
I guess my short question is: how do I get audio input and output to work on Electron?

**Comment by curcuz** [comment] 2016-09-23 19:42
Hi @edoardo849 - I think whatever is the issue, it's not related with Electron itself, but with X11-based applications - can you give me details about what device are you using (I guess raspberrypi), what's the USB mic model?

**Comment by curcuz** [comment] 2016-10-30 18:29
@edoardo849 since I am unable to reproduce without the info requested, I will close this issue soon if no details will be shared

**Comment by curcuz** [comment] 2016-12-01 21:57
no answer since more than 2 months ago, closing

**Closed as completed by curcuz** 2016-12-01 21:57 UTC
Labels: more-information-needed
